spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 链接try数据库
    url: jdbc:mysql://127.0.0.1:3306/try?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456